name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Add aarch64 target
        run: rustup target add aarch64-unknown-none

      - name: Install dependencies
        run: cargo fetch

      - name: Run tests
        run: cargo test --verbose
